import random
places = ["Biology department offices",
"Sprague first floor",
"HSA dept staff room",
"Physics dept first floor",
"Chem dept second floor",
"Outdoor area in front of sprague",
"Admin/business office first floor",
"The entirety of shan is really well finished",
"Hoch interior is amazing",
"Hide something in a food line?",
"The rusty statue",
"West Dorm courtyard",
"West dorm lounge",
"West dorm legacy suites?",
"South Dorm courtyard",
"South dorm lounge",
"South dorm rooms?",
"East dorm courtyard",
"East dorm lounge",
"East dorm time suck?",
"North dorm is pretty plain tbh",
"Purple duck",
"Lac desk",
"Lac basketball court",
"Basketball court next to east",
"CS grutoring room (lac 2nd floor)",
"Sontag lounge",
"Sontag courtyard",
"Atwood courtyard",
"Greenhouse behind atwood",
"Drinkward lounge",
"Linde courtyard",
"Linde lounge",
"Case courtyard",
"Case lounge",
"Case L corners?",]
choices = 10

print(random.sample(places, choices))
